import * as fs from "fs";
import * as path from "path";
import { analyzeProject } from "../analyzers/project-analyzer.js";

export type AnalyzeProjectArgs = {
  projectPath: string;
};

export async function handleAnalyzeProject(
  args: unknown
): Promise<{ content: Array<{ type: "text"; text: string }> }> {
  const { projectPath } = args as AnalyzeProjectArgs;
  if (!projectPath || typeof projectPath !== "string") {
    return {
      content: [
        {
          type: "text",
          text: JSON.stringify({ error: "projectPath is required and must be a string" }),
        },
      ],
    };
  }
  const projectInfo = await analyzeProject(projectPath);

  // For Spring Boot projects, export a single API spec markdown file.
  // This is a side-effect (creates/updates a file in the target project root).
  const apiSpecPath = path.join(projectPath, "API_SPEC.md");
  const md = buildApiSpecMarkdown(projectInfo);
  try {
    fs.writeFileSync(apiSpecPath, md, "utf-8");
  } catch {
    // If we can't write (permissions), still return the analysis in the response.
  }

  return {
    content: [
      {
        type: "text",
        text: JSON.stringify(
          {
            ...projectInfo,
            apiSpecPath,
          },
          null,
          2
        ),
      },
    ],
  };
}

function buildApiSpecMarkdown(projectInfo: any): string {
  const endpoints = projectInfo?.report?.endpoints as
    | Array<{
        httpMethod: string;
        path: string;
        controllerClass: string;
        methodName: string;
        sourceFile: string;
      }>
    | undefined;

  const configKeys = projectInfo?.report?.configKeys as string[] | undefined;
  const buildTool = projectInfo?.report?.buildTool as string | undefined;

  const lines: string[] = [];
  lines.push(`# API Specification`);
  lines.push(``);
  lines.push(`## Detected Build Tool`);
  lines.push(`${buildTool ?? "unknown"}`);
  lines.push(``);
  lines.push(`## Endpoints (Spring Boot - best-effort)`);
  lines.push(``);

  if (!endpoints || endpoints.length === 0) {
    lines.push(`No endpoints detected.`);
    lines.push(``);
  } else {
    // Group by controller for readability
    const byController = new Map<string, typeof endpoints>();
    for (const e of endpoints) {
      const arr = byController.get(e.controllerClass) ?? [];
      arr.push(e);
      byController.set(e.controllerClass, arr);
    }
    for (const [controller, list] of byController.entries()) {
      lines.push(`### ${controller}`);
      lines.push(``);
      lines.push(`| Method | Path | Java Method | Source |`);
      lines.push(`|---|---|---|---|`);
      for (const e of list) {
        lines.push(
          `| ${e.httpMethod} | \`${e.path}\` | \`${e.methodName}\` | \`${e.sourceFile}\` |`
        );
      }
      lines.push(``);
    }
  }

  lines.push(`## Configuration Keys`);
  lines.push(``);
  if (!configKeys || configKeys.length === 0) {
    lines.push(`No configuration keys detected.`);
  } else {
    for (const k of configKeys.slice(0, 500)) {
      lines.push(`- ${k}`);
    }
    if (configKeys.length > 500) {
      lines.push(`- ...and ${configKeys.length - 500} more`);
    }
  }

  lines.push(``);
  lines.push(`---`);
  lines.push(`Generated by mcp-test-generator (best-effort parsing).`);

  return lines.join("\n");
}
